# Thank you charm team, I love you guys
Output demo.gif

Require echo

Set Shell "bash"
Set FontSize 32
Set Width 1600
Set Height 900

Type "go run ./cmd/tui" Sleep 500ms  Enter Sleep 2s Type "l" Sleep 2s Type "l" Sleep 2s Type "h" Sleep 500ms Type "h" Sleep 500ms Type "h" Sleep 500ms Type "j" Sleep 500ms Enter Sleep 1s Type "f" Sleep 1s Type "j" Sleep 500ms Type "j" Sleep 2s Type "q" Sleep 100ms Type "k"

Sleep 3s
