services:
  server:
    build: .
    container_name: go-server
    ports:
      - "8080:8080"
    dns:
      - "8.8.8.8"
      - "1.1.1.1"
    environment:
      - TZ=America/New_York
    # restart: unless-stopped

